### PR TITLE
Remove reference to psycopg2 from default param value, function body

### LINKED ISSUE #369: Default parameter value breaks pytest if psycopg not installed
The default value for the `isolation_level` parameter introduced in #358 breaks pytest if psycopg is not installed.

To reproduce: install pytest and pytest-postgresql, then run `pytest`. The result is an AttributeError: `AttributeError: 'bool' object has no attribute 'extensions'`. Cause: when psycopg2 is not installed, the `psycopg2` identifier has the value `False` ([ref](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/compat.py#L9)). The error happens [here](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/factories.py#L219) and [here](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/janitor.py#L27).

Rationale: although pytest-postgresql requires psycopg2, installing it *without* psycopg2 should not affect the proper functioning of pytest - i.e., the current behavior appears to be an unintended and unexpected side effect.

In our case, we install psycopg2 conditionally; however, installing pytest-postgresql conditionally would be inconvenient. (https://github.com/galaxyproject/galaxy)

Here's one possible solution: 
For the [second case](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/janitor.py#L27) it's enough to move the reference to `psycopg2.extensions` to the method body, which is not executed at import time. 
For the [first case](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/factories.py#L219) that won't work, so I would suggest using `None` as the default value. However, as long as the default is set in `janitor.py` (second case), the default value is retained, so the behavior as per #358 is unchanged.

I'll submit a PR with the proposed solution. Thank you for considering this!

### PR DESCRIPTION
**Pull request by ic4f**
Fixes #369.

The default value for the isolation_level parameter introduced in #358 breaks pytest if psycopg2 is not installed. See #369 for detailed rationale. The proposed solution removes the reference to psycopg2 from factories.py and moves it into the method body in janitor.py. The original behavior is preserved.

### CODE REVIEW

File: src/pytest_postgresql/factories.py [hunk 1]
```diff
@@ -225,7 +225,6 @@ def postgresql(
     :param db_name: database name
     :param load: SQL to automatically load into our test database
     :param isolation_level: optional postgresql isolation level
-                            defaults to ISOLATION_LEVEL_AUTOCOMMIT
```
Comment (fizyk) [inline src/pytest_postgresql/factories.py:228]: Keep that info, and what's more, I'd still keep within here an or to enforce it. Otherwise we loose the information on what's the default, since that function is not really related to the janitor itself and we can't say: for kwargs information look at janitor.

**Review by fizyk — CHANGES_REQUESTED** [review]

**Comment by fizyk** [comment]
other than I'm okay with everything :)

File: src/pytest_postgresql/factories.py (hunk 1 above)
Comment (ic4f) [reply src/pytest_postgresql/factories.py]: Restored the line.
Sorry, but what 'or' are you referring to? If it's [this one](https://github.com/ClearcodeHQ/pytest-postgresql/pull/370/files#diff-47a715ffd93e4dc187da7b1a66fb6f41b7dc05427479c92d61409665dec52dc0R46), it won't work here: unless I am mistaken, pytest immediately parses the function body, so a reference to `psycopg2.*` will break it.

Comment (fizyk) [reply src/pytest_postgresql/factories.py]: function bodies are not parsed, unless being executed. If it would be the case then [this](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/factories.py#L241) wouldn't work either.

Comment (ic4f) [reply src/pytest_postgresql/factories.py]: The body of the function is executed by pytest (it locates and integrates plugins on startup, as far as i understand), it's called from here https://github.com/pytest-dev/pytest/blob/master/src/_pytest/assertion/rewrite.py#L129
Referring to `psycopg2` works because that identifier exists (see #369), but it points to a boolean, not a module.

**Comment by fizyk** [comment]
Thanks for the fix, I've merged it. Have some followup commit and I'll prepare a patch release then

**Comment by ic4f** [comment]
Thank you - very much appreciated!
