### ISSUE TITLE
Default parameter value breaks pytest if psycopg not installed

### ISSUE THREAD

**Issue by ic4f** [ClearcodeHQ/pytest-postgresql#369]
The default value for the `isolation_level` parameter introduced in #358 breaks pytest if psycopg is not installed.

To reproduce: install pytest and pytest-postgresql, then run `pytest`. The result is an AttributeError: `AttributeError: 'bool' object has no attribute 'extensions'`. Cause: when psycopg2 is not installed, the `psycopg2` identifier has the value `False` ([ref](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/compat.py#L9)). The error happens [here](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/factories.py#L219) and [here](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/janitor.py#L27).

Rationale: although pytest-postgresql requires psycopg2, installing it *without* psycopg2 should not affect the proper functioning of pytest - i.e., the current behavior appears to be an unintended and unexpected side effect.

In our case, we install psycopg2 conditionally; however, installing pytest-postgresql conditionally would be inconvenient. (https://github.com/galaxyproject/galaxy)

Here's one possible solution: 
For the [second case](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/janitor.py#L27) it's enough to move the reference to `psycopg2.extensions` to the method body, which is not executed at import time. 
For the [first case](https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/src/pytest_postgresql/factories.py#L219) that won't work, so I would suggest using `None` as the default value. However, as long as the default is set in `janitor.py` (second case), the default value is retained, so the behavior as per #358 is unchanged.

I'll submit a PR with the proposed solution. Thank you for considering this!
